#!/bin/bash

echo "🔍 Checking CI/CD Pipeline Status..."
echo ""
echo "📊 Pipeline Details:"
echo "• Repository: sadaf-jamal-au27/filmpro-infra"
echo "• Branch: master (production)"
echo "• Trigger: Push with formatted Terraform files"
echo ""
echo "🔗 Monitor your deployment:"
echo "• GitHub Actions: https://github.com/sadaf-jamal-au27/filmpro-infra/actions"
echo "• Latest Workflow: https://github.com/sadaf-jamal-au27/filmpro-infra/actions/workflows/ci-cd.yml"
echo ""
echo "⏱️ Expected Pipeline Steps:"
echo "1. ✅ Terraform Format Check (should pass now)"
echo "2. 🔄 Terraform Validation"
echo "3. 🔒 Security Scan (Checkov)"
echo "4. 🏗️ Production Deployment"
echo "5. 🎉 Release Creation"
echo ""
echo "🎯 Expected Output:"
echo "• Jenkins Server URL"
echo "• GitHub Release with deployment details"
echo "• Infrastructure ready for use"
