#!/bin/bash
# Quick pipeline monitoring script

echo "🔍 Monitoring CI/CD Pipeline Status..."
echo "📍 Repository: sadaf-jamal-au27/filmpro-infra"
echo "🌿 Branch: master"
echo ""
echo "🔗 Links to monitor:"
echo "   • GitHub Actions: https://github.com/sadaf-jamal-au27/filmpro-infra/actions"
echo "   • Latest Workflow: https://github.com/sadaf-jamal-au27/filmpro-infra/actions/workflows/ci-cd.yml"
echo ""
echo "📋 Pipeline Jobs that will run:"
echo "   ✅ 1. Terraform Validation and Security (Checkov scan)"
echo "   🚀 2. Deploy to Production (master branch detected)"
echo ""
echo "⏱️  Expected Timeline:"
echo "   • Validation: ~2-3 minutes"
echo "   • Deployment: ~3-5 minutes"
echo "   • Total: ~5-8 minutes"
echo ""
echo "📊 What to watch for:"
echo "   • ✅ All checks pass (format, validate, security)"
echo "   • 🔐 AWS OIDC authentication succeeds"
echo "   • 🏗️  Terraform init with S3 backend works"
echo "   • 🚀 Infrastructure deployment completes"
echo "   • 🎉 Release creation with Jenkins URL"
echo ""
echo "🔴 If pipeline fails:"
echo "   • Check AWS OIDC role configuration"
echo "   • Verify S3 bucket permissions"
echo "   • Review Terraform syntax"
echo "   • Check GitHub secrets configuration"
